#!/bin/bash

S3SYBC_CMD="aws s3 sync"

S3SYNC_CONFDIR="/etc/s3sync"
_S3SYNC_STANDALONE=0
_S3SYNC_CONFS=""
_S3SYNC_DRYRUN=0
_S3SYNC_S3EXTRAOPTS=""
_S3SYNC_SRCPATH=""
_S3SYNC_DSTPATH=""

do_reset_vars()
{
	S3SYNC_DRYRUN=0
	S3SYNC_S3EXTRAOPTS=""
	S3SYNC_SRCPATH=""
	S3SYNC_DSTPATH=""
}

do_s3_sync()
{
	[ ${S3SYNC_DRYRUN} -eq 1 ] && S3SYNC_DRYRUN_OPT=--dryrun
	echo "aws s3 sync ${S3SYNC_DRYRUN_OPT}" "${S3SYNC_S3EXTRAOPTS}" "${S3SYNC_SRCPATH}" "${S3SYNC_DSTPATH}"
}

do_help()
{
	cat << EOF
	Usage: $0 [params...] [conf(s)..]

		{-h|--help}
			Print this help and exit.

		--conf file.conf
			Load the provided configuration file.
			
		--conf-dir ${S3SYNC_CONFDIR}
			Set the configurtion dir (default ${S3SYNC_CONFDIR})

		{--dest|--to} destination
			Set the destination directory (or Amazon S3 Bucket) in standalone mode.
			
		--dry-run
			Enable the dry-run mode. Use this to test your configuration.

		--extra-opts "extra options"
			Pass the options to "aws s3 sync" tool.
		
		{--source|--from} source
			Set the source directory (or Amazon S3 Bucket) in standalone mode.


EOF
}

# Parsing command line

set -- `getopt -n $0 -o h --long help,conf:,conf-dir:,dest:,to:,dry-run,extra-opts:,source:,from: -- "$@"`

if [ $? -eq 0 ]; then
	while [ $# -ne 0 ]; do
		case "$1" in
			-h|--help)
				do_help
				exit 0
				;;
			--conf)
				shift
				_S3SYNC_CONFS="${_S3SYNC_CONFS} $1"
				;;
			--conf-dir)
				shift
				S3SYNC_CONFDIR=$1
				;;
			--dest|--to)
				shift
				_S3SYNC_DESTPATH="$1"
				_S3SYNC_STANDALONE=1
				;;
			--dry-run)
				_S3SYNC_DRYRUN=1
				;;
			--extra-opts)
				shift
				_S3SYNC_S3_EXTRAOPTS="${_S3SYNC_S3_EXTRAOPTS} $1"
				;;
			--source|--from)
				shift
				_S3SYNC_SRCPATH="$1"
				_S3SYNC_STANDALONE=1
				;;
			--)
				;;
			*)
				_S3SYNC_CONFS="${_S3SYNC_CONFS} $1"
				exit 1
				;;
		esac
		shift
	done
else
	echo error
fi

if [ ${_S3SYNC_STANDALONE} -eq 1 ]; then
	S3SYNC_DRYRUN=${_S3SYNC_DRYRUN}
	S3SYNC_S3EXTRAOPTS="${_S3SYNC_S3EXTRAOPTS}"
	S3SYNC_SRCPATH="${_S3SYNC_SRCPATH}"
	S3SYNC_DSTPATH="${_S3SYNC_DSTPATH}"
	do_s3_sync
else
	[ -z "${_S3SYNC_CONFS}" ] && _S3SYNC_CONFS="$(eval echo ${S3SYNC_CONFDIR}/*.conf)"

	for S3SYNC_CONF in ${_S3SYNC_CONFS}; do
		if [ -f "${S3SYNC_CONF}" ]; then
			do_reset_vars
			. "${S3SYNC_CONF}"
			if [ $_S3SYNC_DRYRUN -eq 1 ]; then
				S3SYNC_DRYRUN=1
			fi
			do_s3_sync
		fi
	done
fi

