#!/bin/bash

S3SYNC_CMD="aws s3 sync"
S3SYNC_CONFDIR="/etc/s3sync/conf"
S3SYNC_CONF="default"
S3SYNC_CONFFILE=""
S3SYNC_DO="help"

S3SYNC_DESCRIPTION=""
S3SYNC_DRYRUN=1
S3SYNC_ENABLE=0
S3SYNC_SRCPATH=""
S3SYNC_DSTPATH=""
S3SYNC_EXCLUDE=""
S3SYNC_INCLUDE=""
S3SYNC_S3EXTRAOPTS=""
S3SYNC_STORAGECLASS=""
S3SYNC_AWS_USERNAME=""
S3SYNC_AWS_ACCESSKEYID=""
S3SYNC_AWS_SECRETACCESSKEY=""
S3SYNC_AWS_REGION=""
S3SYNC_AWS_PROFILE=""

# Ghost variables
_S3SYNC_DESCRIPTION=""
_S3SYNC_DRYRUN=1
_S3SYNC_ENABLE=0
_S3SYNC_SRCPATH=""
_S3SYNC_DSTPATH=""
_S3SYNC_S3EXTRAOPTS=""
_S3SYNC_STORAGECLASS=""
_S3SYNC_EXCLUDE=""
_S3SYNC_INCLUDE=""
_S3SYNC_AWS_USERNAME=""
_S3SYNC_AWS_ACCESSKEYID=""
_S3SYNC_AWS_SECRETACCESSKEY=""
_S3SYNC_AWS_REGION=""
_S3SYNC_AWS_PROFILE=""

_S3SYNC_DESCRIPTION_FORCED=0
_S3SYNC_DRYRUN_FORCED=0
_S3SYNC_ENABLE_FORCED=0
_S3SYNC_SRCPATH_FORCED=0
_S3SYNC_DSTPATH_FORCED=0
_S3SYNC_INCLUDE_FORCED=0
_S3SYNC_EXCLUDE_FORCED=0
_S3SYNC_S3EXTRAOPTS_FORCED=0
_S3SYNC_STORAGECLASS_FORCED=0
_S3SYNC_AWS_USERNAME_FORCED=0
_S3SYNC_AWS_ACCESSKEYID_FORCED=0
_S3SYNC_AWS_SECRETACCESSKEY_FORCED=0
_S3SYNC_AWS_REGION_FORCED=0
_S3SYNC_AWS_PROFILE_FORCED=0

do_clar_ghostvars()
{
	_S3SYNC_DESCRIPTION=""
	_S3SYNC_DRYRUN=1
	_S3SYNC_ENABLE=0
	_S3SYNC_S3EXTRAOPTS=""
	_S3SYNC_SRCPATH=""
	_S3SYNC_DSTPATH=""
	_S3SYNC_STORAGECLASS=""
	_S3SYNC_EXCLUDE=""
	_S3SYNC_INCLUDE=""
	_S3SYNC_AWS_USERNAME=""
	_S3SYNC_AWS_ACCESSKEYID=""
	_S3SYNC_AWS_SECRETACCESSKEY=""
	_S3SYNC_AWS_REGION=""
	_S3SYNC_AWS_PROFILE=""
}

do_clear_vars()
{
	S3SYNC_DESCRIPTION=""
	S3SYNC_DRYRUN=1
	S3SYNC_ENABLE=0
	S3SYNC_S3EXTRAOPTS=""
	S3SYNC_SRCPATH=""
	S3SYNC_DSTPATH=""
	S3SYNC_STORAGECLASS=""
	S3SYNC_EXCLUDE=""
	S3SYNC_INCLUDE=""
	S3SYNC_AWS_USERNAME=""
	S3SYNC_AWS_ACCESSKEYID=""
	S3SYNC_AWS_SECRETACCESSKEY=""
	S3SYNC_AWS_REGION=""
	S3SYNC_AWS_PROFILE=""
}

do_set_vars()
{
	[ ${_S3SYNC_DESCRIPTION_FORCED} -eq 1 ] && S3SYNC_DESCRIPTION="${_S3SYNC_DESCRIPTION}"
	[ ${_S3SYNC_DRYRUN_FORCED} -eq 1 ] && S3SYNC_DRYRUN=${_S3SYNC_DRYRUN}
	[ ${_S3SYNC_ENABLE_FORCED} -eq -1 ] && S3SYNC_ENABLE=${_S3SYNC_ENABLE}
	[ ${_S3SYNC_SRCPATH_FORCED} -eq 1 ] && S3SYNC_SRCPATH="${_S3SYNC_SRCPATH}"
	[ ${_S3SYNC_DSTPATH_FORCED} -eq 1 ] && S3SYNC_DSTPATH="${_S3SYNC_DSTPATH}"
	[ ${_S3SYNC_EXCLUDE_FORCED} -eq 1 ] && S3SYNC_EXCLUDE="${_S3SYNC_EXCLUDE}"
	[ ${_S3SYNC_INCLUDE_FORCED} -eq 1 ] && S3SYNC_INCLUDE="${_S3SYNC_INCLUDE}"
	[ ${_S3SYNC_S3EXTRAOPTS_FORCED} -eq 1 ] && S3SYNC_S3EXTRAOPTS="${_S3SYNC_S3EXTRAOPTS}"
	[ ${_S3SYNC_STORAGECLASS_FORCED} -eq 1 ] && S3SYNC_STORAGECLASS="${_S3SYNC_STORAGECLASS}"
	[ ${_S3SYNC_AWS_USERNAME_FORCED} -eq 1 ] && S3SYNC_AWS_USERNAME="${_S3SYNC_AWS_USERNAME}"
	[ ${_S3SYNC_AWS_ACCESSKEYID_FORCED} -eq 1 ] && S3SYNC_AWS_ACCESSKEYID="${_S3SYNC_AWS_ACCESSKEYID}"
	[ ${_S3SYNC_AWS_SECRETACCESSKEY_FORCED} -eq 1 ] && S3SYNC_AWS_SECRETACCESSKEY="${_S3SYNC_AWS_SECRETACCESSKEY}"
	[ ${_S3SYNC_AWS_REGION_FORCED} -eq 1 ] && S3SYNC_AWS_REGION="${_S3SYNC_AWS_REGION}"
	[ ${_S3SYNC_AWS_PROFILE_FORCED} -eq 1 ] && S3SYNC_AWS_PROFILE="${_S3SYNC_AWS_PROFILE}"
}

do_write_conf()
{
	cat > $1 << EOF
S3SYNC_DESCRIPTION="${S3SYNC_DESCRIPTION}"
S3SYNC_DRYRUN=${S3SYNC_DRYRUN}
S3SYNC_ENABLE=${S3SYNC_ENABLE}
S3SYNC_SRCPATH="${S3SYNC_SRCPATH}"
S3SYNC_DSTPATH="${S3SYNC_DSTPATH}"
S3SYNC_EXCLUDE="${S3SYNC_EXCLUDE}"
S3SYNC_INCLUDE="${S3SYNC_INCLUDE}"
S3SYNC_S3EXTRAOPTS="${S3SYNC_S3EXTRAOPTS}"
S3SYNC_STORAGECLASS="${S3SYNC_STORAGECLASS}"
S3SYNC_AWS_USERNAME="${S3SYNC_AWS_USERNAME}"
S3SYNC_AWS_ACCESSKEYID="${S3SYNC_AWS_ACCESSKEYID}"
S3SYNC_AWS_SECRETACCESSKEY="${S3SYNC_AWS_SECRETACCESSKEY}"
S3SYNC_AWS_REGION="${S3SYNC_AWS_REGION}"
S3SYNC_AWS_PROFILE="${S3SYNC_AWS_PROFILE}"
EOF
}

do_set_conffile()
{
	local CONF="$1"
	[ -z "${CONF}" ] && CONF="default"
	S3SYNC_CONFFILE="${S3SYNC_CONFDIR}/${CONF}.conf"
}

do_modify_conf()
{
	do_set_conffile "${S3SYNC_CONF}"
	[ -f "${S3SYNC_CONFFILE}" ] && . "${S3SYNC_CONFFILE}"
	do_set_vars
	do_write_conf "${S3SYNC_CONFFILE}"
}

do_generate_conf()
{
	do_set_conffile "${S3SYNC_CONF}"
	do_clear_vars
	if [ ! -f ${S3SYNC_CONFFILE} ]; then
		do_write_conf "${S3SYNC_CONFFILE}"
	fi
}

do_execute()
{
	do_set_conffile "${S3SYNC_CONF}"
	if [ -f "${S3SYNC_CONFFILE}" ]; then
		[ -f "${S3SYNC_CONFFILE}" ] && . "${S3SYNC_CONFFILE}"
		do_set_vars
		if [ ${S3SYNC_ENABLE} -eq 1 ]; then
			local AWS_PROFILE_OPT="${S3SYNC_AWS_PROFILE:+--profile ${S3SYNC_AWS_PROFILE}}"
			local AWS_REGION_OPT="${S3SYNC_AWS_REGION:+--region ${S3SYNC_AWS_REGION}}"
			local AWS_INCLUDE_OPT=""
			set -f
			for i in ${S3SYNC_INCLUDE}; do
				AWS_INCLUDE_OPT="${AWS_INCLUDE_OPT} --include \"$i\""
			done
			set +f
			local AWS_EXCLUDE_OPT=""
			set -f
			for i in ${S3SYNC_EXCLUDE}; do
				AWS_EXCLUDE_OPT="${AWS_EXCLUDE_OPT} --exclude \"$i\""
			done
			set +f
			local AWS_DRYRUN_OPT
			[ ${S3SYNC_DRYRUN} -eq 1 ] && AWS_DRYRUN_OPT="--dryrun"
			local AWS_STORAGECLASS_OPT="${S3SYNC_STORAGECLASS:+--storage-class ${S3SYNC_STORAGECLASS}}"

			AWS_ACCESS_KEY_ID="${S3SYNC_AWS_ACCESSKEYID}" \
			AWS_SECRET_ACCESS_KEY="${S3SYNC_AWS_SECRETACCESSKEY}" \
			eval aws s3 sync \
							${AWS_PROFILE_OPT} \
							${AWS_REGION_OPT} \
							${AWS_EXCLUDE_OPT} \
							${AWS_INCLUDE_OPT} \
							${AWS_DRYRUN_OPT} \
							${AWS_STORAGECLASS_OPT} \
							${S3SYNC_S3EXTRAOPTS} \
										"${S3SYNC_SRCPATH}" "${S3SYNC_DSTPATH}"
		fi
	else
		echo "Configuration ${S3SYNC_CONFFILE} doesn't exist."
		exit 1
	fi
}

do_help()
{
	cat << EOF

	Usage: s3sync {PARAMETER...} ACTION

	ACTIONs:
		create	Create a new configuration file.
		modify	Modify an existing configuration file.
		execute	Execute using an existing configuration file.

	PARAMETERs:
		--help
			Show this help and exit.
		--conf-dir=Directory
			Set the root of configurations directory (default: ${S3SYNC_CONFDIR}).
		--conf=configuration_name
			Use the configuration name to setup the environment.
		--description=Description
			Set the configuration's description.
		--dry-run
			Simulate the command.
		--no-dry-run
			Execute the command.
		--enable
			Enable the configuration.
		--disable
			Disable the configuration.
		--src=Directory
		--source=Directory
		--from=Directory
			Set the source directory/bucket
		--dst=Directory
		--dest=Directory
		--destination=Directory
		--to=Directory
			Set the destination directory/bucket
		--exclude-pattern=pattern
			Add an exclude string pattern.
		--include-pattern=pattern
			Add an include string pattern.
		--extra-opts=string
			Extra options to pass 'aws' command.
		--storage-class=string
			Set the storage class.
		--aws-user-name=string
			Set the AWS User-Name.
		--aws-access-key-id=string
			Set the AWS Access Key Identifier.
		--aws-secret-access-key=string
			Set the AWS Secrete Access Key string.
		--aws-region=string
			Set the AWS region.
		--aws-profile=string
			Set the AWS profile name.

EOF
}

# Parsing command line

set -- `getopt -n $0 -o h -u --longoptions " \
	help,
	conf-dir:,
	conf:,
	description:,
	dry-run,
	no-dry-run,
	enable,
	disable,
	src:,source:,from:,
	dst:,dest:,destination:,to:,
	exclude-pattern:,
	include-pattern:,
	extra-opts:,
	storage-class:
	aws-user-name:
	aws-access-key-id:
	aws-secret-access-key:
	aws-region:
	aws-profile:
	" -- "$@"`

if [ $? -eq 0 ]; then
	while [ $# -ne 0 ]; do
		case "$1" in
			-h|--help)
				do_help
				exit 0
				;;
			--conf-dir)
				shift
				S3SYNC_CONFDIR="${1}"
				;;
			--conf)
				shift
				S3SYNC_CONF="${1}"
				;;
			--description)
				shift
				_S3SYNC_DESCRIPTION="${1}"
				_S3SYNC_DESCRIPTION_FORCED=1
				;;
			--dry-run)
				_S3SYNC_DRYRUN=1
				_S3SYNC_DRYRUN_FORCED=1
				;;
			--no-dry-run)
				_S3SYNC_DRYRUN=0
				_S3SYNC_DRYRUN_FORCED=1
				;;
			--enable)
				_S3SYNC_ENABLE=1
				_S3SYNC_ENABLE_FORCED=1
				;;
			--disable)
				_S3SYNC_ENABLE=0
				_S3SYNC_ENABLE_FORCED=1
				;;
			--src|--source|--from)
				shift
				_S3SYNC_SRCPATH="${1}"
				_S3SYNC_SRCPATH_FORCED=1
				;;
			--dst|--dest|--destination|--to)
				shift
				_S3SYNC_DSTPATH="${1}"
				_S3SYNC_DSTPATH_FORCED=1
				;;
			--exclude-pattern)
				shift
				_S3SYNC_EXCLUDE="${_S3SYNC_EXCLUDE:+${_S3SYNC_EXCLUDE} }${1}"
				_S3SYNC_EXCLUDE_FORCED=1
				;;
			--include-pattern)
				shift
				_S3SYNC_INCLUDE="${_S3SYNC_INCLUDE:+${_S3SYNC_INCLUDE} }${1}"
				_S3SYNC_INCLUDE_FORCED=1
				;;
			--extra-opts)
				shift
				_S3SYNC_S3EXTRAOPTS="${1}"
				_S3SYNC_S3EXTRAOPTS_FORCED=1
				;;
			--storage-class)
				shift
				_S3SYNC_STORAGECLASS="${1}"
				_S3SYNC_STORAGECLASS_FORCED=1
				;;
			--aws-user-name)
				shift
				_S3SYNC_AWS_USERNAME="${1}"
				_S3SYNC_AWS_USERNAME_FORCED=1
				;;
			--aws-access-key-id)
				shift
				_S3SYNC_AWS_ACCESSKEYID="${1}"
				_S3SYNC_AWS_ACCESSKEYID_FORCED=1
				;;
			--aws-secret-access-key)
				shift
				_S3SYNC_AWS_SECRETACCESSKEY="${1}"
				_S3SYNC_AWS_SECRETACCESSKEY_FORCED=1
				;;
			--aws-region)
				shift
				_S3SYNC_AWS_REGION="${1}"
				_S3SYNC_AWS_REGION_FORCED=1
				;;
			--aws-profile)
				shift
				_S3SYNC_AWS_PROFILE="${1}"
				_S3SYNC_AWS_PROFILE_FORCED=1
				;;
			--)
				S3SYNC_ACTION=1
				;;
			create)
				do_generate_conf "${S3SYNC_CONF}"
				exit 0
				;;
			modify)
				do_modify_conf "${S3SYNC_CONF}"
				exit 0
				;;
			execute)
				do_execute
				exit 0
				;;
		esac
		shift
	done
else
	echo error
fi
